import type { User, Project, Task, Sprint, Workspace, Notification } from '@/types'

export const mockDelay = (ms = 400) =>
  new Promise((resolve) => setTimeout(resolve, ms))

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    email: 'alex.morgan@projectflow.io',
    name: 'Alex Morgan',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    role: 'admin',
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'user-2',
    email: 'sarah.chen@projectflow.io',
    name: 'Sarah Chen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    role: 'member',
    createdAt: '2024-01-20T08:00:00Z',
  },
  {
    id: 'user-3',
    email: 'james.wilson@projectflow.io',
    name: 'James Wilson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=james',
    role: 'member',
    createdAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'user-4',
    email: 'priya.patel@projectflow.io',
    name: 'Priya Patel',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    role: 'member',
    createdAt: '2024-02-10T08:00:00Z',
  },
]

export const MOCK_WORKSPACE: Workspace = {
  id: 'ws-1',
  name: 'Acme Corp',
  slug: 'acme-corp',
  ownerId: 'user-1',
  plan: 'pro',
  projectCount: 3,
  memberCount: 4,
  members: [
    { userId: 'user-1', name: 'Alex Morgan', email: 'alex.morgan@projectflow.io', role: 'owner', joinedAt: '2024-01-15T08:00:00Z' },
    { userId: 'user-2', name: 'Sarah Chen', email: 'sarah.chen@projectflow.io', role: 'admin', joinedAt: '2024-01-20T08:00:00Z' },
    { userId: 'user-3', name: 'James Wilson', email: 'james.wilson@projectflow.io', role: 'member', joinedAt: '2024-02-01T08:00:00Z' },
    { userId: 'user-4', name: 'Priya Patel', email: 'priya.patel@projectflow.io', role: 'member', joinedAt: '2024-02-10T08:00:00Z' },
  ],
  createdAt: '2024-01-15T08:00:00Z',
}

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Frontend Redesign',
    key: 'FRD',
    description: 'Complete overhaul of the customer-facing web application with new design system and improved UX.',
    color: 'blue',
    icon: 'code',
    workspaceId: 'ws-1',
    ownerId: 'user-1',
    members: [
      { userId: 'user-1', name: 'Alex Morgan', email: 'alex.morgan@projectflow.io', role: 'owner', joinedAt: '2024-01-15T08:00:00Z' },
      { userId: 'user-2', name: 'Sarah Chen', email: 'sarah.chen@projectflow.io', role: 'admin', joinedAt: '2024-01-20T08:00:00Z' },
      { userId: 'user-3', name: 'James Wilson', email: 'james.wilson@projectflow.io', role: 'member', joinedAt: '2024-02-01T08:00:00Z' },
    ],
    sprintCount: 3,
    taskCount: 24,
    completedTaskCount: 11,
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-06-20T14:30:00Z',
    isArchived: false,
  },
  {
    id: 'proj-2',
    name: 'API Gateway v2',
    key: 'AGW',
    description: 'Migrate and modernize the API gateway infrastructure with improved rate limiting and auth.',
    color: 'green',
    icon: 'zap',
    workspaceId: 'ws-1',
    ownerId: 'user-2',
    members: [
      { userId: 'user-2', name: 'Sarah Chen', email: 'sarah.chen@projectflow.io', role: 'owner', joinedAt: '2024-01-20T08:00:00Z' },
      { userId: 'user-4', name: 'Priya Patel', email: 'priya.patel@projectflow.io', role: 'member', joinedAt: '2024-02-10T08:00:00Z' },
    ],
    sprintCount: 2,
    taskCount: 18,
    completedTaskCount: 7,
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-06-18T10:00:00Z',
    isArchived: false,
  },
  {
    id: 'proj-3',
    name: 'Mobile App',
    key: 'MOB',
    description: 'Native mobile application for iOS and Android platforms.',
    color: 'purple',
    icon: 'layers',
    workspaceId: 'ws-1',
    ownerId: 'user-1',
    members: [
      { userId: 'user-1', name: 'Alex Morgan', email: 'alex.morgan@projectflow.io', role: 'owner', joinedAt: '2024-01-15T08:00:00Z' },
      { userId: 'user-3', name: 'James Wilson', email: 'james.wilson@projectflow.io', role: 'member', joinedAt: '2024-02-01T08:00:00Z' },
      { userId: 'user-4', name: 'Priya Patel', email: 'priya.patel@projectflow.io', role: 'member', joinedAt: '2024-02-10T08:00:00Z' },
    ],
    sprintCount: 1,
    taskCount: 12,
    completedTaskCount: 3,
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-06-15T16:00:00Z',
    isArchived: false,
  },
]

export const MOCK_SPRINTS: Sprint[] = [
  {
    id: 'sprint-1',
    name: 'Sprint 1',
    goal: 'Complete navigation redesign and component library setup',
    projectId: 'proj-1',
    status: 'completed',
    startDate: '2024-05-06',
    endDate: '2024-05-17',
    taskIds: ['task-1', 'task-2', 'task-3', 'task-4'],
    completedTaskIds: ['task-1', 'task-2', 'task-3', 'task-4'],
    createdAt: '2024-05-01T08:00:00Z',
    completedAt: '2024-05-17T18:00:00Z',
  },
  {
    id: 'sprint-2',
    name: 'Sprint 2',
    goal: 'Implement dashboard and analytics views',
    projectId: 'proj-1',
    status: 'active',
    startDate: '2024-05-20',
    endDate: '2024-05-31',
    taskIds: ['task-5', 'task-6', 'task-7', 'task-8', 'task-9'],
    completedTaskIds: ['task-5'],
    createdAt: '2024-05-15T08:00:00Z',
  },
  {
    id: 'sprint-3',
    name: 'Sprint 3',
    goal: 'User authentication and profile management',
    projectId: 'proj-1',
    status: 'planning',
    taskIds: [],
    completedTaskIds: [],
    createdAt: '2024-05-20T08:00:00Z',
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Setup Tailwind CSS design tokens',
    description: 'Define color palette, typography scale, spacing system and export as design tokens for use across the app.',
    type: 'task',
    status: 'done',
    priority: 'high',
    projectId: 'proj-1',
    sprintId: 'sprint-1',
    assigneeId: 'user-2',
    assigneeName: 'Sarah Chen',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-1', name: 'Design', color: '#8b5cf6' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [
      { id: 'act-1', type: 'created', description: 'Task created', userId: 'user-1', userName: 'Alex Morgan', timestamp: '2024-05-01T09:00:00Z' },
      { id: 'act-2', type: 'status_change', description: 'Status changed to Done', userId: 'user-2', userName: 'Sarah Chen', timestamp: '2024-05-14T15:00:00Z', meta: { from: 'in_progress', to: 'done' } },
    ],
    storyPoints: 3,
    createdAt: '2024-05-01T09:00:00Z',
    updatedAt: '2024-05-14T15:00:00Z',
    order: 1,
  },
  {
    id: 'task-2',
    title: 'Build reusable Button component',
    description: 'Create Button with variants: primary, secondary, ghost, danger. Support sizes sm/md/lg and loading state.',
    type: 'task',
    status: 'done',
    priority: 'medium',
    projectId: 'proj-1',
    sprintId: 'sprint-1',
    assigneeId: 'user-3',
    assigneeName: 'James Wilson',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=james',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-2', name: 'Frontend', color: '#3b82f6' }],
    subtasks: [
      { id: 'sub-1', title: 'Write unit tests', isCompleted: true },
      { id: 'sub-2', title: 'Add Storybook stories', isCompleted: true },
    ],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 2,
    createdAt: '2024-05-02T09:00:00Z',
    updatedAt: '2024-05-15T11:00:00Z',
    order: 2,
  },
  {
    id: 'task-3',
    title: 'Fix navigation z-index issue on mobile',
    description: 'The sidebar nav overlaps with modal dialogs on viewport widths below 768px.',
    type: 'bug',
    status: 'done',
    priority: 'critical',
    projectId: 'proj-1',
    sprintId: 'sprint-1',
    assigneeId: 'user-2',
    assigneeName: 'Sarah Chen',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    reporterId: 'user-3',
    reporterName: 'James Wilson',
    labels: [{ id: 'label-3', name: 'Bug', color: '#ef4444' }, { id: 'label-4', name: 'Mobile', color: '#f97316' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 1,
    createdAt: '2024-05-08T14:00:00Z',
    updatedAt: '2024-05-10T09:00:00Z',
    order: 3,
  },
  {
    id: 'task-4',
    title: 'Implement responsive grid layout for dashboard',
    description: 'Dashboard cards should reflow gracefully from 4 columns on desktop to 2 on tablet and 1 on mobile.',
    type: 'story',
    status: 'done',
    priority: 'medium',
    projectId: 'proj-1',
    sprintId: 'sprint-1',
    assigneeId: 'user-1',
    assigneeName: 'Alex Morgan',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-2', name: 'Frontend', color: '#3b82f6' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 5,
    createdAt: '2024-05-03T10:00:00Z',
    updatedAt: '2024-05-16T17:00:00Z',
    order: 4,
  },
  {
    id: 'task-5',
    title: 'Integrate Recharts for analytics page',
    description: 'Add burndown chart, task distribution pie chart, and sprint velocity bar chart to the analytics view.',
    type: 'story',
    status: 'done',
    priority: 'high',
    projectId: 'proj-1',
    sprintId: 'sprint-2',
    assigneeId: 'user-4',
    assigneeName: 'Priya Patel',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-5', name: 'Analytics', color: '#06b6d4' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 5,
    createdAt: '2024-05-20T10:00:00Z',
    updatedAt: '2024-05-26T12:00:00Z',
    order: 1,
  },
  {
    id: 'task-6',
    title: 'Build notification dropdown component',
    description: 'Notification bell with dropdown showing recent alerts. Support read/unread state with badge count.',
    type: 'task',
    status: 'in_progress',
    priority: 'medium',
    projectId: 'proj-1',
    sprintId: 'sprint-2',
    assigneeId: 'user-2',
    assigneeName: 'Sarah Chen',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-2', name: 'Frontend', color: '#3b82f6' }],
    subtasks: [
      { id: 'sub-3', title: 'Bell icon with badge', isCompleted: true },
      { id: 'sub-4', title: 'Dropdown list UI', isCompleted: true },
      { id: 'sub-5', title: 'Mark all as read action', isCompleted: false },
    ],
    comments: [
      {
        id: 'comment-1',
        content: 'Should we support browser push notifications as well, or just in-app for now?',
        authorId: 'user-2',
        authorName: 'Sarah Chen',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
        createdAt: '2024-05-22T11:00:00Z',
        isEdited: false,
      },
      {
        id: 'comment-2',
        content: 'Just in-app for this sprint. We can add push in a later sprint.',
        authorId: 'user-1',
        authorName: 'Alex Morgan',
        authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
        createdAt: '2024-05-22T11:30:00Z',
        isEdited: false,
      },
    ],
    attachments: [],
    activity: [],
    storyPoints: 3,
    dueDate: '2024-05-30',
    createdAt: '2024-05-20T10:00:00Z',
    updatedAt: '2024-05-23T09:00:00Z',
    order: 2,
  },
  {
    id: 'task-7',
    title: 'Implement global search with keyboard shortcut',
    description: 'Cmd+K opens a search palette. Results include tasks, projects, and team members with fuzzy matching.',
    type: 'story',
    status: 'todo',
    priority: 'high',
    projectId: 'proj-1',
    sprintId: 'sprint-2',
    assigneeId: 'user-3',
    assigneeName: 'James Wilson',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=james',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-2', name: 'Frontend', color: '#3b82f6' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 8,
    dueDate: '2024-05-31',
    createdAt: '2024-05-20T10:00:00Z',
    updatedAt: '2024-05-20T10:00:00Z',
    order: 1,
  },
  {
    id: 'task-8',
    title: 'Dark mode implementation',
    description: 'Add dark mode toggle. Persist preference to localStorage. Support system preference detection.',
    type: 'task',
    status: 'review',
    priority: 'low',
    projectId: 'proj-1',
    sprintId: 'sprint-2',
    assigneeId: 'user-1',
    assigneeName: 'Alex Morgan',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    reporterId: 'user-2',
    reporterName: 'Sarah Chen',
    labels: [{ id: 'label-2', name: 'Frontend', color: '#3b82f6' }, { id: 'label-1', name: 'Design', color: '#8b5cf6' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 2,
    createdAt: '2024-05-21T10:00:00Z',
    updatedAt: '2024-05-26T16:00:00Z',
    order: 1,
  },
  {
    id: 'task-9',
    title: 'Performance audit and lazy loading',
    description: 'Run Lighthouse audit. Implement route-based code splitting. Lazy load heavy components like charts.',
    type: 'task',
    status: 'testing',
    priority: 'medium',
    projectId: 'proj-1',
    sprintId: 'sprint-2',
    assigneeId: 'user-4',
    assigneeName: 'Priya Patel',
    assigneeAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-6', name: 'Performance', color: '#22c55e' }],
    subtasks: [
      { id: 'sub-6', title: 'Run initial Lighthouse audit', isCompleted: true },
      { id: 'sub-7', title: 'Add route-based code splitting', isCompleted: true },
      { id: 'sub-8', title: 'Verify bundle size reduction', isCompleted: false },
    ],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 3,
    createdAt: '2024-05-22T10:00:00Z',
    updatedAt: '2024-05-27T10:00:00Z',
    order: 1,
  },
  {
    id: 'task-10',
    title: 'User onboarding flow',
    description: 'Multi-step onboarding for new users: workspace creation, team invites, first project setup.',
    type: 'epic',
    status: 'backlog',
    priority: 'high',
    projectId: 'proj-1',
    reporterId: 'user-1',
    reporterName: 'Alex Morgan',
    labels: [{ id: 'label-7', name: 'UX', color: '#f59e0b' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 13,
    createdAt: '2024-05-25T10:00:00Z',
    updatedAt: '2024-05-25T10:00:00Z',
    order: 1,
  },
  {
    id: 'task-11',
    title: 'Export tasks to CSV/Excel',
    description: 'Allow users to export filtered task lists to CSV and Excel formats.',
    type: 'story',
    status: 'backlog',
    priority: 'low',
    projectId: 'proj-1',
    reporterId: 'user-2',
    reporterName: 'Sarah Chen',
    labels: [],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 3,
    createdAt: '2024-05-26T10:00:00Z',
    updatedAt: '2024-05-26T10:00:00Z',
    order: 2,
  },
  {
    id: 'task-12',
    title: 'API rate limit error handling',
    description: 'Show appropriate UI when API rate limits are hit. Add retry logic with exponential backoff.',
    type: 'bug',
    status: 'backlog',
    priority: 'medium',
    projectId: 'proj-1',
    reporterId: 'user-3',
    reporterName: 'James Wilson',
    labels: [{ id: 'label-3', name: 'Bug', color: '#ef4444' }],
    subtasks: [],
    comments: [],
    attachments: [],
    activity: [],
    storyPoints: 2,
    createdAt: '2024-05-27T10:00:00Z',
    updatedAt: '2024-05-27T10:00:00Z',
    order: 3,
  },
]

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'task_assigned',
    title: 'Task assigned to you',
    message: 'Alex Morgan assigned "Implement global search" to you',
    isRead: false,
    userId: 'user-3',
    link: '/projects/proj-1/board',
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'task_commented',
    title: 'New comment on your task',
    message: 'Alex Morgan commented on "Build notification dropdown"',
    isRead: false,
    userId: 'user-2',
    link: '/projects/proj-1/board',
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'sprint_started',
    title: 'Sprint 2 started',
    message: 'Sprint 2 has been started in Frontend Redesign project',
    isRead: true,
    userId: 'user-1',
    link: '/projects/proj-1/board',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'notif-4',
    type: 'member_joined',
    title: 'New team member',
    message: 'Priya Patel joined the Acme Corp workspace',
    isRead: true,
    userId: 'user-1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
]
